
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programaACTIVADA AIRE ALARMA ALTAVOZ AND ASIGNACION BOOL BRILLO CERRADURA COLOR DISCRETO DO ELSE EMAIL EMAIL_NOTIF END ESTADO EVERY FECHA FOCO HORA IF IGUAL LUX MAYOR MAYORIGUAL MENOR MENORIGUAL MENSAJE MODO MUTE NOIGUAL NOMBRE NOT OR PERCENT PERSIANA POSICION PUNTO RELOJ SENSOR_HUMEDAD SENSOR_HUMO SENSOR_LUZ SENSOR_MOVIMIENTO SENSOR_TEMP TEMP TEMP_ACT TEMP_OBJ TEXTO THEN TIEMPO TIME VOLUMEN WHENprograma : lista_instruccioneslista_instrucciones : instruccionlista_instrucciones : instruccion lista_instruccionesinstruccion : bloque_when \n| bloque_every \n| bloque_if \n| asignacionbloque_when : WHEN condicion DO lista_acciones ENDbloque_if : IF condicion THEN lista_acciones ELSE lista_acciones END \n| IF condicion THEN lista_acciones END\nbloque_every : EVERY TIEMPO  DO  lista_acciones ENDlista_acciones : accionlista_acciones : accion lista_accionesaccion : asignacionasignacion : FOCO PUNTO ESTADO ASIGNACION BOOLasignacion : FOCO PUNTO BRILLO ASIGNACION PERCENTasignacion : FOCO PUNTO COLOR ASIGNACION NOMBREcondicion : comp_sensorcomp_sensor : SENSOR_TEMP comparacion TEMP\n| SENSOR_HUMEDAD comparacion PERCENT\n| SENSOR_LUZ comparacion LUX\n| SENSOR_MOVIMIENTO comparacion BOOL\n| SENSOR_HUMO comparacion BOOLcomparacion : IGUAL\n| NOIGUAL\n| MAYOR\n| MENOR\n| MAYORIGUAL\n| MENORIGUAL'
    
_lr_action_items = {'WHEN':([0,3,4,5,6,7,53,55,57,58,59,60,62,],[8,8,-4,-5,-6,-7,-8,-11,-10,-15,-16,-17,-9,]),'EVERY':([0,3,4,5,6,7,53,55,57,58,59,60,62,],[9,9,-4,-5,-6,-7,-8,-11,-10,-15,-16,-17,-9,]),'IF':([0,3,4,5,6,7,53,55,57,58,59,60,62,],[10,10,-4,-5,-6,-7,-8,-11,-10,-15,-16,-17,-9,]),'FOCO':([0,3,4,5,6,7,23,35,36,41,42,53,55,56,57,58,59,60,62,],[11,11,-4,-5,-6,-7,11,11,11,11,-14,-8,-11,11,-10,-15,-16,-17,-9,]),'$end':([1,2,3,4,5,6,7,12,53,55,57,58,59,60,62,],[0,-1,-2,-4,-5,-6,-7,-3,-8,-11,-10,-15,-16,-17,-9,]),'SENSOR_TEMP':([8,10,],[15,15,]),'SENSOR_HUMEDAD':([8,10,],[16,16,]),'SENSOR_LUZ':([8,10,],[17,17,]),'SENSOR_MOVIMIENTO':([8,10,],[18,18,]),'SENSOR_HUMO':([8,10,],[19,19,]),'TIEMPO':([9,],[20,]),'PUNTO':([11,],[22,]),'DO':([13,14,20,43,44,45,46,47,],[23,-18,35,-19,-20,-21,-22,-23,]),'THEN':([14,21,43,44,45,46,47,],[-18,36,-19,-20,-21,-22,-23,]),'IGUAL':([15,16,17,18,19,],[25,25,25,25,25,]),'NOIGUAL':([15,16,17,18,19,],[26,26,26,26,26,]),'MAYOR':([15,16,17,18,19,],[27,27,27,27,27,]),'MENOR':([15,16,17,18,19,],[28,28,28,28,28,]),'MAYORIGUAL':([15,16,17,18,19,],[29,29,29,29,29,]),'MENORIGUAL':([15,16,17,18,19,],[30,30,30,30,30,]),'ESTADO':([22,],[37,]),'BRILLO':([22,],[38,]),'COLOR':([22,],[39,]),'TEMP':([24,25,26,27,28,29,30,],[43,-24,-25,-26,-27,-28,-29,]),'PERCENT':([25,26,27,28,29,30,31,51,],[-24,-25,-26,-27,-28,-29,44,59,]),'LUX':([25,26,27,28,29,30,32,],[-24,-25,-26,-27,-28,-29,45,]),'BOOL':([25,26,27,28,29,30,33,34,50,],[-24,-25,-26,-27,-28,-29,46,47,58,]),'ASIGNACION':([37,38,39,],[50,51,52,]),'END':([40,41,42,48,49,54,58,59,60,61,],[53,-12,-14,55,57,-13,-15,-16,-17,62,]),'ELSE':([41,42,49,54,58,59,60,],[-12,-14,56,-13,-15,-16,-17,]),'NOMBRE':([52,],[60,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_instrucciones':([0,3,],[2,12,]),'instruccion':([0,3,],[3,3,]),'bloque_when':([0,3,],[4,4,]),'bloque_every':([0,3,],[5,5,]),'bloque_if':([0,3,],[6,6,]),'asignacion':([0,3,23,35,36,41,56,],[7,7,42,42,42,42,42,]),'condicion':([8,10,],[13,21,]),'comp_sensor':([8,10,],[14,14,]),'comparacion':([15,16,17,18,19,],[24,31,32,33,34,]),'lista_acciones':([23,35,36,41,56,],[40,48,49,54,61,]),'accion':([23,35,36,41,56,],[41,41,41,41,41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> lista_instrucciones','programa',1,'p_programa','parser.py',7),
  ('lista_instrucciones -> instruccion','lista_instrucciones',1,'p_lista_instrucciones_una','parser.py',11),
  ('lista_instrucciones -> instruccion lista_instrucciones','lista_instrucciones',2,'p_lista_instrucciones_varias','parser.py',15),
  ('instruccion -> bloque_when','instruccion',1,'p_instruccion','parser.py',19),
  ('instruccion -> bloque_every','instruccion',1,'p_instruccion','parser.py',20),
  ('instruccion -> bloque_if','instruccion',1,'p_instruccion','parser.py',21),
  ('instruccion -> asignacion','instruccion',1,'p_instruccion','parser.py',22),
  ('bloque_when -> WHEN condicion DO lista_acciones END','bloque_when',5,'p_bloque_when','parser.py',26),
  ('bloque_if -> IF condicion THEN lista_acciones ELSE lista_acciones END','bloque_if',7,'p_bloque_if','parser.py',30),
  ('bloque_if -> IF condicion THEN lista_acciones END','bloque_if',5,'p_bloque_if','parser.py',31),
  ('bloque_every -> EVERY TIEMPO DO lista_acciones END','bloque_every',5,'p_bloque_every','parser.py',39),
  ('lista_acciones -> accion','lista_acciones',1,'p_lista_acciones_una','parser.py',43),
  ('lista_acciones -> accion lista_acciones','lista_acciones',2,'p_lista_acciones_varias','parser.py',47),
  ('accion -> asignacion','accion',1,'p_accion','parser.py',51),
  ('asignacion -> FOCO PUNTO ESTADO ASIGNACION BOOL','asignacion',5,'p_asignacion_foco_estado','parser.py',55),
  ('asignacion -> FOCO PUNTO BRILLO ASIGNACION PERCENT','asignacion',5,'p_asignacion_foco_brillo','parser.py',59),
  ('asignacion -> FOCO PUNTO COLOR ASIGNACION NOMBRE','asignacion',5,'p_asignacion_foco_color','parser.py',63),
  ('condicion -> comp_sensor','condicion',1,'p_condicion','parser.py',67),
  ('comp_sensor -> SENSOR_TEMP comparacion TEMP','comp_sensor',3,'p_comp_sensor','parser.py',71),
  ('comp_sensor -> SENSOR_HUMEDAD comparacion PERCENT','comp_sensor',3,'p_comp_sensor','parser.py',72),
  ('comp_sensor -> SENSOR_LUZ comparacion LUX','comp_sensor',3,'p_comp_sensor','parser.py',73),
  ('comp_sensor -> SENSOR_MOVIMIENTO comparacion BOOL','comp_sensor',3,'p_comp_sensor','parser.py',74),
  ('comp_sensor -> SENSOR_HUMO comparacion BOOL','comp_sensor',3,'p_comp_sensor','parser.py',75),
  ('comparacion -> IGUAL','comparacion',1,'p_comparacion','parser.py',79),
  ('comparacion -> NOIGUAL','comparacion',1,'p_comparacion','parser.py',80),
  ('comparacion -> MAYOR','comparacion',1,'p_comparacion','parser.py',81),
  ('comparacion -> MENOR','comparacion',1,'p_comparacion','parser.py',82),
  ('comparacion -> MAYORIGUAL','comparacion',1,'p_comparacion','parser.py',83),
  ('comparacion -> MENORIGUAL','comparacion',1,'p_comparacion','parser.py',84),
]
